---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cluster-user-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgClAfWaQSII0+7KKjx/F9Dsb2pYiHP8jFJG7PKSQ1tqriRF9SDbaXFv7Px9SDDyPcbfzMpogtlDuz2zjnEQy+2SzO0y2lAcR7ExiHeq3ufAszF9zafEkPsTHYDHrjI+DSaUbBLvy7zNDXz0HnQ9z8GaBfgOBGUJX1PaL3/Sc5FEGHefhVD+MHBMMeOoAYfT2cY6Y5OaZyWIGAcf4Jmr7KO3GBDa5JQwLqjnHJI3fHjyPW+1YgzwFdpfCaj7MW4IldkXvIdVGQR667+6mhvda338Zq4p9C8kTIQYoT9s2p4k2vCqm1NGVxvG39n8NDWhap10UgmEmJK+xxG/dtF/ZfhYF4PBY9gjab6FCbdwU2nh/02GqAXVBMy6uQ0r0ayD4T0DJeN3vIkY7u1CjTrg9X1KyTet4thPS4czNX7twoV0MfTH8gukkasZA/B1u7QOpDKwbIYbFTNYtLmXcfvr/KIt3j3bGrWFGaSfXVWFB3hS4j4jANRchDUSlmmfWpnPmzNR/WplT8OQ1GfOLlbqy0K1Vn3CEzQ+985rH2FB4lh80n9xs/RJmTAt/jViFfiNdawJ8AjsN9ioP0YwW4fES+MsBCdx6KSJ0tmmKsqAQZIUgHqsNIR1Qx2eHrftg/Ic1LslgB/wFovPWSIyBLNwxw9f4NXkh7uqzguMiWG2Cs39UJ3pbDhAMuLnPaf8NZHiW/N/pT7KJMw5+oeM+OXBsK26pSJYehzqL20jLihLZbvdTdNOpMy8XC6M0OdDroqDcvOuBldprAhX9pSB1rI=
    username: AgBuk+w5tjci31r3AzcZCstejCruwsevecc98f6KxRrPA3DX8wV+jnD85XuOzi+Dn6AOcG3KBfIzDlq+w8DpFwFL0mz94ADG+R9aKkJ3OFGowQavbWYWzPsWmeH8AO72HpsvhtmI+OpMZSY0R8JdNBklPfUqYA9Pitvp+oDBBugG/+t/jrQRV5oGY/OcZibyrKFos3KH4Gny9VGsIzrPOew7fhjh7Bfuxg6LkFHSygIVqZmQ/pRTq5IxEn0eBMWMhL/G/m84PTm3okE7jT1Eh5E2z3n1AUlKKr8Pj9ro+NhaFeQxqmrebOWqjyS0/lAPlfzoI1tUBiLUbN0363QwG/c2RvCuezQXPPyzd6oXHpuEB7KfyEzkzii2lLAVrSHjYJtOPEraITRsiGS9QMaA315p1Mfz26XXtzgMyuSf8oSu6BVStvo9IM+X5ZgJWjZYb4F6fZmbSMKnDqHLeyPF4F0yNfULlllB2h1TBnYzFW4ijZ9ZlBfxeEcLfRPqueT8QvqBX43DUxw68TG0C/GyeLf6tYLp9d8IXa0qFOmI2REoiH2JjPi7sZx2dB+/C1IdKZDFCLPK4h7pGfR/9/Mq/iE22TP+X14RqEekUG8nP0uaZoyLC3YxBddGbps3ox2oAg3XlO65tIh8RyOEzyyIxickRewNsFNaolIDfOz7iYLuFuREI899CtmqCKdNXKh5nj3vCk5LtA==
  template:
    metadata:
      creationTimestamp: null
      name: cluster-user-auth
      namespace: flux-system
